{'result': {'order': '', 'problem_id': {'link': 'https://dev34374.service-now.com/api/now/table/problem/9d3a266ac6112287004e37fb2ceb0133', 'value': '9d3a266ac6112287004e37fb2ceb0133'}, 'assignment_group': {'link': 'https://dev34374.service-now.com/api/now/table/sys_user_group/287ebd7da9fe198100f92cc8d1d2154e', 'value': '287ebd7da9fe198100f92cc8d1d2154e'}, 'work_notes': '', 'business_stc': '', 'follow_up': '', 'calendar_duration': '', 'subcategory': '', 'work_start': '', 'closed_by': '', 'sys_mod_count': '17', 'escalation': '3', 'reopen_count': '', 'business_duration': '', 'activity_due': '2017-03-22 21:51:11', 'incident_state': '3', 'category': 'network', 'skills': '', 'comments': '', 'hold_reason': '2', 'upon_reject': '', 'active': 'true', 'delivery_plan': '', 'notify': '1', 'additional_assignee_list': '', 'sys_updated_by': 'admin', 'sys_id': '9d385017c611228701d22104cc95c371', 'number': 'INC0000002', 'rfc': '', 'opened_at': '2016-12-14 23:07:12', 'short_description': 'Unable to get to network file shares', 'cmdb_ci': {'link': 'https://dev34374.service-now.com/api/now/table/cmdb_ci/b0c25d1bc0a800090168be1bfcdcd759', 'value': 'b0c25d1bc0a800090168be1bfcdcd759'}, 'sys_domain': {'link': 'https://dev34374.service-now.com/api/now/table/sys_user_group/global', 'value': 'global'}, 'correlation_display': '', 'sys_tags': '', 'work_end': '', 'close_notes': '', 'parent': '', 'caused_by': '', 'approval_history': '', 'impact': '1', 'description': "User can't get to any of his files on the file server.\n\t\t", 'location': {'link': 'https://dev34374.service-now.com/api/now/table/cmn_location/108486c7c611227500b093211aa88dcc', 'value': '108486c7c611227500b093211aa88dcc'}, 'time_worked': '', 'resolved_at': '', 'assigned_to': {'link': 'https://dev34374.service-now.com/api/now/table/sys_user/46ca0887a9fe19810191e08e51927ebf', 'value': '46ca0887a9fe19810191e08e51927ebf'}, 'watch_list': '', 'contact_type': '', 'delivery_task': '', 'child_incidents': '', 'business_service': '', 'knowledge': 'false', 'resolved_by': '', 'comments_and_work_notes': '', 'approval': '', 'sla_due': '', 'urgency': '1', 'closed_at': '', 'sys_created_by': 'pat', 'made_sla': 'false', 'sys_class_name': 'incident', 'sys_updated_on': '2017-03-22 19:51:11', 'severity': '1', 'due_date': '', 'state': '3', 'company': '', 'caller_id': {'link': 'https://dev34374.service-now.com/api/now/table/sys_user/5137153cc611227c000bbd1bd8cd2005', 'value': '5137153cc611227c000bbd1bd8cd2005'}, 'parent_incident': '', 'upon_approval': '', 'expected_start': '', 'user_input': '', 'group_list': '', 'work_notes_list': '', 'sys_domain_path': '/', 'reassignment_count': '1', 'approval_set': '', 'calendar_stc': '', 'close_code': '', 'correlation_id': '', 'opened_by': {'link': 'https://dev34374.service-now.com/api/now/table/sys_user/681ccaf9c0a8016400b98a06818d57c7', 'value': '681ccaf9c0a8016400b98a06818d57c7'}, 'priority': '1', 'sys_created_on': '2015-07-11 22:30:06'}}